'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, ArrowDown, RotateCcw, Ruler, MoveHorizontal, MoveVertical, CircleHelp, Check, Layers, Route, Bike } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Switch } from '@/components/ui/switch';
import { FRAME_PRESETS, FRAME_REFERENCE, frameGeometry } from '@/lib/frame';
import { useFrameTools } from '@/lib/use-frame-tools';

const n = (v: number | readonly number[]) => typeof v === 'number' ? v : v[0];
const delta = (v: number) => `${v > 0 ? '+' : ''}${v}`;
const round = (v: number) => Number(v.toFixed(3));

function FrameDiagram({ stack, reach, spacers, stem, ghost }: { stack: number; reach: number; spacers: number; stem: number; ghost: boolean }) {
  const x = 320 + reach * .5, y = 410 - stack * .5;
  const refX = 320 + FRAME_REFERENCE.reach * .5, refY = 410 - FRAME_REFERENCE.stack * .5;
  const geometry = frameGeometry(stack, reach, spacers, stem);
  const spaceX = round(x - spacers * Math.cos(73 * Math.PI / 180) * .5);
  const spaceY = round(y - spacers * Math.sin(73 * Math.PI / 180) * .5);
  const handX = round(320 + geometry.handReach * .5), handY = round(410 - geometry.handStack * .5);
  const frame = (hx: number, hy: number) => `M138 380L258 185L${hx} ${hy + 10}L${hx + 25} ${hy + 85}L320 410L258 185M138 380L320 410M${hx + 25} ${hy + 85}L${hx + 110} 380`;
  return <svg viewBox="0 0 800 590" className="frame-diagram" role="img" aria-label={`以五通中心为原点，到头管上端中心的垂直距离 Stack ${stack} 毫米，水平距离 Reach ${reach} 毫米。STR ${geometry.str.toFixed(3)}。`}><defs><pattern id="frame-grid" width="25" height="25" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#7b8d9a" opacity=".25"/></pattern><marker id="arrow-orange" viewBox="0 0 8 8" refX="4" refY="4" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L8 4L0 8" fill="none" stroke="#f8aa73"/></marker><marker id="arrow-blue" viewBox="0 0 8 8" refX="4" refY="4" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L8 4L0 8" fill="none" stroke="#9cc9e0"/></marker></defs><rect width="800" height="590" fill="url(#frame-grid)"/><path d="M5 516H795" stroke="#465662" strokeDasharray="3 7"/>{[138, x + 110].map((cx, i) => <g key={i}><circle cx={cx} cy="380" r="132" fill="none" stroke="#536574" strokeWidth="7"/><circle cx={cx} cy="380" r="124" fill="none" stroke="#41535f" strokeWidth="1"/><path d={`M${cx - 124} 380H${cx + 124}M${cx} 256V504M${cx - 88} 292L${cx + 88} 468M${cx - 88} 468L${cx + 88} 292`} stroke="#41535f"/></g>)}{ghost && <path d={frame(refX, refY)} fill="none" stroke="#9dabb5" strokeWidth="3" strokeDasharray="7 7" opacity=".55"/>}<path d={frame(x, y)} fill="none" stroke="#d1dce0" strokeWidth="8" strokeLinecap="round" strokeLinejoin="round"/><path d={`M${x} ${y}L${x + 25} ${y + 85}`} stroke="#eaa576" strokeWidth="10" strokeLinecap="round"/><path d="M258 185L250 153M225 151H275" stroke="#a7b8c2" strokeWidth="7" strokeLinecap="round"/><circle cx="320" cy="410" r="20" fill="#24333f" stroke="#8b9ba8" strokeWidth="2"/><path d="M320 410L346 438H365" stroke="#cad6dc" strokeWidth="5" strokeLinecap="round"/>
    <path d={`M320 410V64M${x} ${y}V64`} stroke="#7495aa" strokeDasharray="4 5" opacity=".8"/><path d={`M320 65H${x}`} stroke="#9cc9e0" strokeWidth="2" markerStart="url(#arrow-blue)" markerEnd="url(#arrow-blue)"/><text x={(320 + x) / 2} y="44" textAnchor="middle" fill="#b6dced" fontSize="17">Reach {reach} mm</text><path d={`M320 410H722M${x} ${y}H722`} stroke="#b78666" strokeDasharray="4 5" opacity=".8"/><path d={`M712 410V${y}`} stroke="#f8aa73" strokeWidth="2" markerStart="url(#arrow-orange)" markerEnd="url(#arrow-orange)"/><text x="735" y={(410 + y) / 2} fill="#ffbb8b" fontSize="17" transform={`rotate(-90 735 ${(410 + y) / 2})`} textAnchor="middle">Stack {stack} mm</text>
    <path d={`M${x} ${y}L${spaceX} ${spaceY}L${handX - 37.5} ${handY}H${handX}`} fill="none" stroke="#bba9dc" strokeWidth="5" strokeLinecap="round"/><circle cx={handX} cy={handY} r="5" fill="#d6c5f4"/><text x={handX + 12} y={handY - 10} fill="#c8b7e6" fontSize="14">示意手位</text><circle cx={x} cy={y} r="6" fill="#ffb580" stroke="#24333f" strokeWidth="2"/><path d={`M${x} ${y}L290 114H80`} fill="none" stroke="#eab083"/><text x="80" y="99" fill="#dfebee" fontSize="14">头管上端中心</text><circle cx="320" cy="410" r="5" fill="#fff"/><path d="M320 410V540H280" fill="none" stroke="#c2d0d6"/><text x="270" y="544" textAnchor="end" fill="#dbe5e9" fontSize="14">五通中心 · 测量原点</text><text x="400" y="576" textAnchor="middle" fill="#a8bbc8" fontSize="14">测的是垂直与水平距离，不是沿着车架管材量长度。</text></svg>;
}

function MeasureControl({ title, value, min, max, onChange, color }: { title: string; value: number; min: number; max: number; onChange: (v: number) => void; color?: string }) {
  const [draft, setDraft] = useState(String(value));
  useEffect(() => setDraft(String(value)), [value]);
  function commitDraft() {
    const candidate = Number(draft);
    const next = draft.trim() && Number.isFinite(candidate) ? Math.max(min, Math.min(max, Math.round(candidate))) : value;
    setDraft(String(next));
    onChange(next);
  }
  return <div className={`measure-control ${color ?? ''}`}><div className="field-heading"><label>{title}</label><span className="number-input"><input aria-label={title} type="number" min={min} max={max} step={1} value={draft} onChange={e => { setDraft(e.target.value); const candidate = e.target.valueAsNumber; if (Number.isInteger(candidate) && candidate >= min && candidate <= max) onChange(candidate); }} onBlur={commitDraft} onKeyDown={e => { if (e.key === 'Enter') e.currentTarget.blur(); }}/><small>mm</small></span></div><Slider aria-label={`${title}滑块`} min={min} max={max} step={1} value={[value]} onValueChange={v => onChange(n(v))}/><div className="range-labels"><span>{min} mm</span><span>{max} mm</span></div></div>;
}

export default function FrameLab() {
  const [stack, setStack] = useState(570), [reach, setReach] = useState(385);
  const [spacers, setSpacers] = useState(20), [stem, setStem] = useState(100), [ghost, setGhost] = useState(true);
  const result = frameGeometry(stack, reach, spacers, stem);
  useFrameTools({ stack, reach, spacers, stem }, value => { setStack(value.stack); setReach(value.reach); setSpacers(value.spacers); setStem(value.stem); });
  const preset = FRAME_PRESETS.find(p => p.stack === stack && p.reach === reach)?.id ?? '';
  function choose(id: string) { const p = FRAME_PRESETS.find(p => p.id === id); if (p) { setStack(p.stack); setReach(p.reach); } }
  const changes = `${result.stackDelta === 0 ? '高度相同' : result.stackDelta > 0 ? `高了 ${result.stackDelta} mm` : `低了 ${-result.stackDelta} mm`}，${result.reachDelta === 0 ? '长度相同' : result.reachDelta > 0 ? `远了 ${result.reachDelta} mm` : `近了 ${-result.reachDelta} mm`}`;
  return <main className="frame-page"><section className="intro"><div><div className="eyebrow"><span/> 实验室 02 / FRAME GEOMETRY</div><h1>车架的高与长，<span>藏着骑姿的答案。</span></h1><p>拖动两个尺寸，看懂 STR。选车时，先找到适合自己的位置。</p></div><a href="#frame-basics" className="intro-link">车架几何看不懂？<br/><span>从两个测量点开始 <ArrowDown size={15}/></span></a></section><div className="lab-grid frame-lab-grid"><section className="simulation frame-simulation"><div className="sim-top"><span>车架几何 · 测量示意</span><span>灰色虚线 = 570 / 385 参考车架</span></div><div className="speed-row"><div><div className="speed-label">Stack-to-Reach Ratio</div><div className="speed-value"><output aria-live="polite">{result.str.toFixed(3)}</output><span>STR</span></div></div><div className="speed-context"><span>{stack} <span>÷</span> {reach}</span><small>同单位相除 · 无单位</small><span className="geometry-badge">比例，不是舒适度评分</span></div></div><FrameDiagram stack={stack} reach={reach} spacers={spacers} stem={stem} ghost={ghost}/><div className="sim-stats"><div><small>垂直高度变化</small><strong>{delta(result.stackDelta)}<span> mm</span></strong></div><div><small>水平长度变化</small><strong>{delta(result.reachDelta)}<span> mm</span></strong></div><div><small>相对参考车架 STR</small><strong>{delta(Number((result.str - 570 / 385).toFixed(3)))}</strong></div></div></section><aside className="settings frame-settings"><div className="settings-title"><h2><Ruler size={19}/> 改变车架，看看位置</h2><button className="reset" onClick={() => { choose('balanced'); setSpacers(20); setStem(100); }}><RotateCcw size={14}/> 重置</button></div><RadioGroup className="choice-row" aria-label="车架几何示例" value={preset} onValueChange={v => choose(String(v))}>{FRAME_PRESETS.map(p => <label key={p.id} className={`choice ${preset === p.id ? 'selected' : ''}`}><RadioGroupItem value={p.id} className="choice-radio" aria-label={p.label}/><span>{p.label}</span></label>)}</RadioGroup><p className="control-note">教学示例，不代表具体车型或行业分界线。</p><MeasureControl title="Stack · 垂直高度" value={stack} min={480} max={660} onChange={setStack}/><p className="control-note">保持 Reach 不变，Stack 越大，头管上端越高。</p><MeasureControl title="Reach · 水平长度" value={reach} min={340} max={450} onChange={setReach} color="blue-control"/><p className="control-note">保持 Stack 不变，Reach 越大，前端离五通越远。</p><label className="ghost-toggle"><Switch checked={ghost} onCheckedChange={setGhost} aria-label="显示参考车架"/><span>显示参考车架</span></label><div className="frame-insight"><small>和参考车架相比</small><h3>{changes}</h3><p>其他设置和骑手条件相同时，更高或更近的前端通常更容易形成较直立的骑姿；更低或更远的前端往往需要更多前倾。混合变化要分别看。</p></div><div className="experiment-buttons"><button disabled={stack > 620} onClick={() => setStack(v => v + 40)}><MoveVertical size={15}/> 只加高 40 mm</button><button disabled={reach < 360} onClick={() => setReach(v => v - 20)}><MoveHorizontal size={15}/> 只缩短 20 mm</button></div></aside></div>
    <section className="frame-basics" id="frame-basics"><div className="section-heading"><div><div className="eyebrow">TWO DISTANCES, ONE RATIO</div><h2>STR 到底怎么算？</h2></div><span className="section-note">不要把头管长度当 Stack，也不要把上管长度当 Reach。</span></div><div className="frame-definition"><article><span className="term-number">01</span><h3><MoveVertical size={19}/> Stack / 堆高</h3><p>从<strong>五通中心</strong>到<strong>头管上端中心</strong>的垂直距离。可以理解为车架前端的“高度”。</p></article><article><span className="term-number">02</span><h3><MoveHorizontal size={19}/> Reach / 前伸量</h3><p>相同两个点之间的水平距离。可以理解为车架前端相对于脚踏轴心的“长度”。</p></article><article className="str-equation"><span className="term-number">03</span><h3>STR = Stack ÷ Reach</h3><strong>{stack} ÷ {reach} = {result.str.toFixed(3)}</strong><p>尺寸都用毫米或都用厘米，结果相同。车架坐标应使用同一种测量口径。</p></article></div></section>
    <section className="same-ratio"><div><div className="eyebrow">一个容易忽略的陷阱</div><h2>STR 一样，车架也可能差很多。</h2><p>540 ÷ 360 和 600 ÷ 400 都是 1.500。后者高了 60 mm、长了 40 mm，不能据此说两台车一样合身。比较 STR 时，也要看绝对尺寸、同类车型与相近尺码。</p></div><div className="same-ratio-options"><button onClick={() => { setStack(540); setReach(360); }} aria-pressed={stack === 540 && reach === 360}><span>示例 A · 较小</span><strong>540 / 360</strong><small>STR 1.500 <ArrowRight size={16}/></small></button><button onClick={() => { setStack(600); setReach(400); }} aria-pressed={stack === 600 && reach === 400}><span>示例 B · 较大</span><strong>600 / 400</strong><small>STR 1.500 <ArrowRight size={16}/></small></button></div></section>
    <section className="cockpit-section"><div className="section-heading"><div><div className="eyebrow">FRAME FIT ≠ HAND POSITION</div><h2>车架不变，手的位置还能变。</h2></div><span className="section-note">调整下方参数，观察图中的紫色手位标记。</span></div><div className="cockpit-grid"><div className="cockpit-controls"><MeasureControl title="把立下垫圈高度" value={spacers} min={0} max={40} onChange={setSpacers}/><MeasureControl title="把立长度" value={stem} min={70} max={130} onChange={setStem}/></div><div className="cockpit-result"><span className="mini-label">车架 STR 始终是</span><strong>{result.str.toFixed(3)}</strong><p>但示意手位已变成：<b>高 {result.handStack.toFixed(0)} mm / 远 {result.handReach.toFixed(0)} mm</b>（相对五通中心）。</p><p>垫圈沿倾斜的舵管向上，也略向后；把立、弯把前伸量和手变安装位置都会影响实际骑姿。</p></div></div><details className="methodology"><summary>手位示意的计算假设 <CircleHelp size={16}/></summary><div><p>简化固定头管角 73°，把立相对水平上扬 6°，弯把及手位水平偏移合计 75 mm。手位高度 = Stack + 垫圈 × sin73° + 把立 × sin6°；手位前伸 = Reach − 垫圈 × cos73° + 把立 × cos6° + 75。图形坐标与这些公式一致。</p><p>未计碗组上盖、把立夹持中心高度、弯把落差、手变安装和握持差异，因此紫色点仅用于说明原理，不是实际装车尺寸或人体 fitting 结果。0–40 mm 是演示范围，允许的垫圈高度以车架、前叉和把立厂商要求为准。</p></div></details></section>
    <section className="comfort-section"><div className="section-heading"><div><div className="eyebrow">COMFORT IS A WHOLE-BIKE QUESTION</div><h2>舒服不是一个数字，是整台车与你的配合。</h2></div></div><div className="comfort-banner"><CircleHelp size={24}/><div><h3>STR 越高，不等于越舒服。</h3><p>过长、过短、过高或过低都可能不适合你。你的身材比例、柔韧性、骑行目标，以及坐垫高度与前后位置，都会改变合适的把位。较高 STR 只是了解车架形状的一条线索。</p></div></div><div className="knowledge-grid"><article><Ruler/><h3>先看尺寸，再看 S / M / L</h3><p>不同品牌的同一码不一定一样大。结合厂商尺码表、跨高和站立间隙，再看 Stack、Reach 及可调整范围，尽量试骑。</p></article><article><Route/><h3>操控也写在几何里</h3><p>头管角、前叉偏移、拖曳距和轴距共同影响转向与稳定性。不能只凭 STR 判断一台车是否灵活，也别直接套用公路车比例评价山地车。</p></article><article><Layers/><h3>材料不是舒适度排名</h3><p>铝、钢、碳纤维和钛各有取舍；结构设计和整车配置同样重要。碳架不必然更舒服，也不应该用材料代替合身程度来选车。</p></article><article><Bike/><h3>别忽略轮胎与接触点</h3><p>轮胎结构、胎宽和胎压会影响路感；车架的轮胎间隙决定可选范围。坐垫、把带、握位和座杆也会改变长时间骑行的体验。</p></article></div><div className="fit-checklist"><h3>小白选车，按这个顺序看</h3><ol><li><Check size={17}/><span>确定用途：通勤、长途、竞速，还是越野。</span></li><li><Check size={17}/><span>先排除明显不合尺寸，确认坐垫和把位能调到合适范围。</span></li><li><Check size={17}/><span>比较 Stack 与 Reach 的绝对数值，再用 STR 辅助理解比例。</span></li><li><Check size={17}/><span>试骑后再决定；持续不适时，可请专业 fitting 人员协助评估。</span></li></ol></div><details className="methodology"><summary>参考资料与使用边界 <CircleHelp size={16}/></summary><div><p>本页采用常规 frame Stack / Reach：五通中心到头管上端中心。厂商的 effective Stack / Reach、Stack+ 等指标可能测到手位或把组，不能混用。</p><p>本页三种预设是教学示例，没有统一的“低于多少竞技、高于多少舒适”的行业分界。未输入人体测量，也不会据 STR 推荐具体尺码或给出舒适度分数。</p><p>参考：<a href="https://www.canyon.com/en-us/blog-content/road-cycling-news/road-bike-geometry-explained/b19102022.html" target="_blank" rel="noreferrer">Canyon：车架几何与测量口径</a>；<a href="https://www.trekbikes.com/us/en_US/owners-manual/fitting-your-bicycle/" target="_blank" rel="noreferrer">Trek：车辆尺寸与骑姿调整</a>。</p></div></details></section>
  </main>;
}
